# Gateway Service - Configuration for all profiles

server:
  port: 8080

spring:
  application:
    name: gateway-service
  
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: asset-service
              uri: ${ASSET_SERVICE_URL:http://asset-service:8080}
              predicates:
                - Path=/api/assets/**

            - id: asset-service-web
              uri: ${ASSET_SERVICE_URL:http://asset-service:8080}
              predicates:
                - Path=/assets/**
              filters:
                - StripPrefix=1

            - id: telemetry-service
              uri: ${TELEMETRY_SERVICE_URL:http://telemetry-service:8080}
              predicates:
                - Path=/api/telemetry/**

            - id: telemetry-service-web
              uri: ${TELEMETRY_SERVICE_URL:http://telemetry-service:8080}
              predicates:
                - Path=/telemetry/**
              filters:
                - StripPrefix=1

            - id: alert-service
              uri: ${ALERT_SERVICE_URL:http://alert-service:8080}
              predicates:
                - Path=/api/alerts/**

            - id: alert-service-web
              uri: ${ALERT_SERVICE_URL:http://alert-service:8080}
              predicates:
                - Path=/alerts/**
              filters:
                - StripPrefix=1

# Additional actuator endpoints for gateway
management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh,gateway,prometheus,metrics,routes

# SpringDoc configuration for aggregated API docs
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: Asset Service
        url: /assets/v3/api-docs
      - name: Telemetry Service
        url: /telemetry/v3/api-docs
      - name: Alert Service
        url: /alerts/v3/api-docs
