# Asset Service - Development Environment
# H2 in-memory database for local development

spring:
  datasource:
    url: jdbc:h2:mem:assets
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

  sql:
    init:
      mode: always

logging:
  level:
    com.greenko.assetservice: DEBUG
    org.hibernate.SQL: DEBUG
