# Telemetry Service - Development Environment

spring:
  datasource:
    url: jdbc:h2:mem:telemetry
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

  sql:
    init:
      mode: always

logging:
  level:
    com.greenko.telemetryservice: DEBUG
    org.hibernate.SQL: DEBUG